pid /tmp/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 128; }
http {
  include /etc/nginx/mime.types;
  access_log /dev/stdout;
  server_tokens off;
  client_body_temp_path /tmp/body;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;
  server {
    listen 8080;
    root /usr/share/nginx/html;
    location / { try_files $uri $uri/ =404; }
    location = /health { default_type text/plain; }
  }
}
